language: android
sudo: required
android:
  components:
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-android-support
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
before_install:
yes | sdkmanager "cmake;3.6.4111459" --licenses
- chmod +x gradlew
- "./gradlew dependencies || true"
script:
- "./gradlew assembleRelease"
before_script:
- wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
- unzip -qq android-ndk-r16b-linux-x86_64.zip
- export ANDROID_NDK_HOME=`pwd`/android-ndk-r16b
- export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
- export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64"
- export PATH=$PATH:${ANDROID_NDK_HOME}
- env
before_deploy:
- ls
deploy:
  provider: releases
  api_key:
    secure: JeSnJfv5wvuO1UO4I+r7pEOmEcKmBmqLd+AzCvND2jZS1GMBeeW0SPhtyjro0Nvx1aSYDNU1AVSJe2Mzm5cGaOWC/BEcUZNQ0kg2fxh0tfRAyphLDP4+H6WcbXxobVfckItdffCYxvnYvLaZylHzUDazggVfmTFAPt1mHFesTOftnu7grAji6hFsQtBpYC+l9IzG9dpFKHnURHSeSV2E4D/iEr829N6JcOFru2cZK0E63OlG+AseiL7rijYZRJ156Z+fVVmtkGriqrp6AqJZYvvH/1ynWLPSw60GhhGlsKH5MaUDsdVuw4YK4kfZrzHupkHAadn+fTdHgoNeU7W1uOb9oEBvovz9ceLlQweHpE2K+gc5bej24mp2jRH1FXKjwQkCkg/x66faiVr+prHeHWOqy4S+28tkKGc8StG3qdNr6B8IyvftV36rKqI5J5ONkzuH36uoYtEwFRqhS5+bZ/O0Ou6GUVy9UuMu5BQ5K6uHl8Sql68GZpG1XyH//72ZfdzyPFJlwFpQQcZSziBkd22x7OQmB5ypag8lPR7a7OjednU5ah94uzVVOQJWlg3lVNxbJdSlHL5JBn+47huLJ9baF9kOVKKYwK5Q4nD4ogRvQNVYtsP0OGETaGVclfcxM85sM5HoQNxvWhSJia5qWZwpGneLJFAQXesgfOrVq/Y=
  file: app/build/outputs/apk/ela/release/elephant_wallet_test.apk
  skip_cleanup: true
  on:
    repo: elastos/Elastos.App.Wallet.Elephant.Android
    branch: dev
    tags: true
notifications:
  email:
  - 15921908346@163.com
  - lifayi@elastos.org
  - xuliting@elastos.org
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore elastostest.jks
  -storepass $storepass -keypass $keypass app/build/outputs/apk/ela/release/app-ela-release-unsigned.apk key0
- jarsigner -verify app/build/outputs/apk/ela/release/app-ela-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/28.0.3/zipalign -v 4 app/build/outputs/apk/ela/release/app-ela-release-unsigned.apk app/build/outputs/apk/ela/release/elephant_wallet_test.apk"
